"""add is_deadline_notified to tasks

Revision ID: 74a145f755af
Revises: 872d64982cb7
Create Date: 2026-09-17 22:34:24.725372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a145f755af'
down_revision: Union[str, Sequence[str], None] = '872d64982cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'tasks',
        sa.Column(
            'is_deadline_notified',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_deadline_notified')
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
