# Generated by Django 5.1.15 on 2026-09-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('status', models.CharField(choices=[('DRAFT', 'Чернетка'), ('CONFIRMED', 'Підтверджено (пошук авто / призначено)'), ('AT_LOADING', 'На завантаженні'), ('IN_TRANSIT', 'В дорозі'), ('AT_CUSTOMS', 'На митниці'), ('AT_UNLOADING', 'На вивантаженні'), ('DELIVERED', 'Доставлено (очікування документів)'), ('DOCS_RECEIVED', 'Документи отримано (на оплаті)'), ('PAID', 'Оплачено / Закрито'), ('CANCELLED', 'Скасовано')], db_index=True, default='DRAFT', max_length=20, verbose_name='Статус заявки')),
                ('responsible_id', models.IntegerField(db_index=True, verbose_name='ID відповідального менеджера')),
                ('manager_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="Ім'я відповідального")),
                ('client_currency', models.CharField(choices=[('UAH', 'Гривня (UAH)'), ('EUR', 'Євро (EUR)'), ('USD', 'Долар США (USD)')], default='UAH', max_length=5, verbose_name='Валюта клієнта')),
                ('client_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна для клієнта')),
                ('carrier_currency', models.CharField(choices=[('UAH', 'Гривня (UAH)'), ('EUR', 'Євро (EUR)'), ('USD', 'Долар США (USD)')], default='UAH', max_length=5, verbose_name='Валюта перевізника')),
                ('carrier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ставка перевізнику')),
                ('payments_term', models.CharField(blank=True, choices=[('PREPAY_100', '100% передоплата до завантаження'), ('ON_LOADING', 'По факту завантаження (в день завантаження)'), ('ON_UNLOADING', 'По факту вивантаження (в день вивантаження)'), ('SCANS_0', 'По скан-копіях документів (день у день)'), ('SCANS_3', 'По скан-копіях протягом 3-х банківських днів'), ('SCANS_5', 'По скан-копіях протягом 5 банківських днів'), ('SCANS_7', 'По скан-копіях протягом 7 банківських днів'), ('ORIG_0', 'По оригіналах документів (день у день)'), ('ORIG_3', 'По оригіналах документів протягом 3-х банківських днів'), ('ORIG_5', 'По оригіналах документів протягом 5 банківських днів'), ('ORIG_7', 'По оригіналах документів протягом 7 банківських днів'), ('ORIG_10', 'По оригіналах документів протягом 10 банківських днів'), ('ORIG_14', 'По оригіналах документів протягом 14 банківських днів'), ('ORIG_21', 'По оригіналах документів протягом 21 банківського дня'), ('CUSTOM', 'Індивідуальні умови (вказати в примітках)')], default='ORIG_7', max_length=20, null=True, verbose_name='Термін оплати')),
                ('border', models.CharField(blank=True, choices=[('PL302020', 'PL302020: Дорогуськ — Ягодин (Вантажний)'), ('PL402010', 'PL402010: Корчова — Краківець'), ('PL302050', 'PL302050: Гребенне — Рава-Руська'), ('PL402020', 'PL402020: Медика — Шегині'), ('PL302040', 'PL302040: Долгобичув — Угринів'), ('PL402030', 'PL402030: Будомєж — Грушів'), ('PL402050', 'PL402050: Мальховіце — Нижанковичі'), ('PL402040', 'PL402040: Кросценко — Смільниця'), ('SK525100', 'SK525100: Вишнє Нємецьке — Ужгород'), ('SK525300', 'SK525300: Убля — Малий Березний'), ('HU322000', 'HU322000: Захонь (Тиса) — Чоп'), ('HU324000', 'HU324000: Берегшурань — Лужанка'), ('HU323000', 'HU323000: Тісабеч — Вилок'), ('HU325000', 'HU325000: Барабаш — Косино'), ('HU321000', 'HU321000: Лонья — Дзвінкове'), ('ROIS4600', 'ROIS4600: Сірет — Порубне'), ('ROCJ3800', 'ROCJ3800: Халмеу — Дякове'), ('ROIS4900', 'ROIS4900: Вікову-де-Сус — Красноїльськ'), ('ROGL4200', 'ROGL4200: Ісакча — Орлівка (Поромна переправа)'), ('ROCJ3700', 'ROCJ3700: Сигіт-Мармароський — Солотвино'), ('OTHER', 'Інший митний пост ЄС')], max_length=20, null=True, verbose_name='Пункт пропуску (NCTS/ЄС)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки до заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.cargo', verbose_name='Партія вантажу')),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'is_carrier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_orders', to='clients.counterparty', verbose_name='Перевізник')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='clients.counterparty', verbose_name='Клієнт / Замовник')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to='directory.contact', verbose_name='Водій')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.trailer', verbose_name='Причіп / Напівпричіп')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='directory.vehicle', verbose_name='Тягач / Авто')),
            ],
            options={
                'verbose_name': 'Заявка / Замовлення',
                'verbose_name_plural': 'Заявки / Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок (1, 2, 3...)')),
                ('stop_type', models.CharField(choices=[('LOADING', 'Завантаження'), ('UNLOADING', 'Вивантаження'), ('CUSTOMS', 'Митне оформлення')], default='LOADING', max_length=20, verbose_name='Тип операції')),
                ('planned_date', models.DateField(verbose_name='Дата прибуття')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки до точки (контакт на складі, рампа)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stops', to='directory.location', verbose_name='Адреса / Локація')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Точка маршруту',
                'verbose_name_plural': 'Точки маршруту',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('order', 'sequence'), name='unique_order_stop_sequence')],
            },
        ),
    ]
