# Generated by Django 5.1.15 on 2026-09-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('legal_form', models.CharField(choices=[('TOV', 'ТОВ (Товариство з обмеженою відповідальністю)'), ('FOP', 'ФОП (Фізична особа-підприємець)'), ('PP', 'ПП (Приватне підприємство)'), ('AT', 'АТ (Акціонерне товариство)'), ('TDV', 'ТДВ (Товариство з додатковою відповідальністю)'), ('KP', 'КП (Комунальне підприємство)')], default='TOV', max_length=20, verbose_name='Юридична форма власності')),
                ('title', models.CharField(max_length=255, verbose_name='Повна юридична назва компанії')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='ЄДРПОУ / ІПН / NIP / VAT ID')),
                ('iban', models.CharField(max_length=60, verbose_name='IBAN / Розрахунковий рахунок')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основний рахунок')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Банківські реквізити',
                'verbose_name_plural': 'Банківські реквізити',
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('title', models.CharField(max_length=255, verbose_name='Загальний опис вантажу')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Небезпечний вантаж (ADR)')),
                ('adr_class', models.CharField(blank=True, choices=[('Відсутній', 'АДР відсутній'), ('1', 'Клас 1: Вибухові речовини та вироби'), ('2.1', 'Клас 2.1: Легкозаймисті гази'), ('2.2', 'Клас 2.2: Незаймисті, нетоксичні гази'), ('2.3', 'Клас 2.3: Токсичні гази'), ('3', 'Клас 3: Легкозаймисті рідини'), ('4.1', 'Клас 4.1: Легкозаймисті тверді речовини, самореактивні речовини'), ('4.2', 'Клас 4.2: Речовини, здатні до самозаймання'), ('4.3', 'Клас 4.3: Речовини, що виділяють займисті гази при контакті з водою'), ('5.1', 'Клас 5.1: Речовини, що окиснюють'), ('5.2', 'Клас 5.2: Органічні пероксиди'), ('6.1', 'Клас 6.1: Токсичні речовини'), ('6.2', 'Клас 6.2: Інфекційні речовини'), ('7', 'Клас 7: Радіоактивні матеріали'), ('8', 'Клас 8: Корозійні (їдкі) речовини'), ('9', 'Клас 9: Інші небезпечні речовини та вироби')], max_length=20, null=True, verbose_name='Клас ADR')),
                ('requires_temperature_control', models.BooleanField(default=False, verbose_name='Температурний режим')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Мін. темп. (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Макс. темп. (°C)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Додаткова інформація')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партія вантажу',
                'verbose_name_plural': 'Партії вантажів',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('country', models.CharField(choices=[('UA', 'Україна'), ('PL', 'Польща'), ('DE', 'Німеччина'), ('SK', 'Словаччина'), ('HU', 'Угорщина'), ('RO', 'Румунія'), ('MD', 'Молдова'), ('FR', 'Франція'), ('IT', 'Італія'), ('ES', 'Іспанія'), ('NL', 'Нідерланди'), ('BE', 'Бельгія'), ('AT', 'Австрія'), ('CZ', 'Чехія'), ('CH', 'Швейцарія'), ('GB', 'Великобританія'), ('IE', 'Ірландія'), ('PT', 'Португалія'), ('LT', 'Литва'), ('LV', 'Латвія'), ('EE', 'Естонія'), ('SE', 'Швеція'), ('NO', 'Норвегія'), ('DK', 'Данія'), ('FI', 'Фінляндія'), ('BG', 'Болгарія'), ('GR', 'Греція'), ('RS', 'Сербія'), ('SI', 'Словенія'), ('HR', 'Хорватія'), ('BA', 'Боснія і Герцеговина'), ('MK', 'Північна Македонія'), ('AL', 'Албанія'), ('ME', 'Чорногорія'), ('TR', 'Туреччина'), ('GE', 'Грузія'), ('AZ', 'Азербайджан'), ('AM', 'Вірменія'), ('KZ', 'Казахстан'), ('UZ', 'Узбекистан'), ('OTHER', 'Інша країна')], db_index=True, default='UA', max_length=5, verbose_name='Країна')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Поштовий індекс')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Місто / Населений пункт')),
                ('address', models.CharField(max_length=255, verbose_name='Вулиця, номер будинку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
                'ordering': ['city', 'address'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Найменування товару')),
                ('packaging_type', models.CharField(choices=[('PX', 'Палета європейська (EPAL / EUR, 120x80)'), ('PD', 'Палета стандартна (120x100)'), ('PB', 'Палета інша'), ('BX', 'Коробка / Ящик (Box / Carton)'), ('43', 'Біг-бег (Big-Bag / Flexible IBC)'), ('DR', 'Бочка (Drum / Barrel)'), ('BG', 'Мішок (Bag)'), ('CA', 'Каністра (Canister)'), ('CR', 'Клітка / Решетування (Crate)'), ('VR', 'Навалом / Насипом (сухий вантаж)'), ('VL', 'Наливом (автоцистерна / наливний)'), ('NE', 'Без упаковки / Негабарит'), ('PK', 'Інший тип упаковки')], default='PX', max_length=5, verbose_name='Основна тара (місце)')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Кількість палет, бочок тощо. Порожньо, якщо насип.', null=True, verbose_name='Кількість основних місць')),
                ('weight_gross_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вага брутто (кг)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Об'єм (м³)")),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Довжина (см)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Висота (см)')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='directory.cargo', verbose_name='Партія вантажу')),
            ],
            options={
                'verbose_name': 'Позиція вантажу',
                'verbose_name_plural': 'Позиції вантажу',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Водій')),
                ('is_client', models.BooleanField(default=False, verbose_name='Клієнт')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Перевізник')),
                ('is_custom_officer', models.BooleanField(default=False, verbose_name='Митний брокер / Офіцер')),
                ('is_warehouse_worker', models.BooleanField(default=False, verbose_name='Співробітник складу')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Прізвище')),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='По-батькові')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Основний номер')),
                ('secondary_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Додатковий номер')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Емейл')),
                ('adr_status', models.CharField(blank=True, choices=[('Відсутній', 'АДР відсутній'), ('1', 'Клас 1: Вибухові речовини та вироби'), ('2.1', 'Клас 2.1: Легкозаймисті гази'), ('2.2', 'Клас 2.2: Незаймисті, нетоксичні гази'), ('2.3', 'Клас 2.3: Токсичні гази'), ('3', 'Клас 3: Легкозаймисті рідини'), ('4.1', 'Клас 4.1: Легкозаймисті тверді речовини, самореактивні речовини'), ('4.2', 'Клас 4.2: Речовини, здатні до самозаймання'), ('4.3', 'Клас 4.3: Речовини, що виділяють займисті гази при контакті з водою'), ('5.1', 'Клас 5.1: Речовини, що окиснюють'), ('5.2', 'Клас 5.2: Органічні пероксиди'), ('6.1', 'Клас 6.1: Токсичні речовини'), ('6.2', 'Клас 6.2: Інфекційні речовини'), ('7', 'Клас 7: Радіоактивні матеріали'), ('8', 'Клас 8: Корозійні (їдкі) речовини'), ('9', 'Клас 9: Інші небезпечні речовини та вироби')], max_length=10, null=True, verbose_name='Клас небезпеки ADR')),
                ('driver_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер водійського посвідчення')),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер паспорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.counterparty', verbose_name='Роботодавець / Компанія')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('plate_number', models.CharField(db_index=True, help_text='Наприклад: AA5678XX', max_length=25, verbose_name='Державний номер причепа')),
                ('body_type', models.CharField(choices=[('TENT_CURTAIN', 'Тент / Штора (завантаження з усіх боків)'), ('MEGA', 'Мегатрейлер (висота від 3м, до 100-105 м³)'), ('REF', 'Рефрижератор (холодильник)'), ('ISOTHERM', 'Ізотерм (термобудка без установки)'), ('CONTAINER', 'Контейнеровоз'), ('TANK', 'Автоцистерна (наливний вантаж)'), ('GRAIN', 'Зерновоз (самоскидний / щеповоз)'), ('DUMP', 'Самоскид'), ('LOWBOY', 'Трал (низькорамний, негабаритний)'), ('FLATBED', 'Відкрита платформа (бортовий)'), ('BUS', 'бус / Бус (до 3.5т)'), ('MICROBUS', 'Бус / Мікроавтобус (до 1.2т)'), ('OTHER', 'Інший тип кузова')], default='TENT_CURTAIN', max_length=30, verbose_name='Тип кузова')),
                ('volume_m3', models.DecimalField(decimal_places=2, default=86.0, help_text='Стандарт тент: 86-92 м³, Мега: 100-105 м³', max_digits=6, verbose_name="Об'єм (м³)")),
                ('capacity_pallets', models.PositiveSmallIntegerField(default=33, help_text='Стандартний напівпричіп вміщує 33 EPAL', verbose_name='Місткість європалет (шт)')),
                ('carrying_capacity_kg', models.PositiveIntegerField(default=22000, verbose_name='Вантажопідйомність (кг)')),
                ('registration_certificate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Свідоцтво про реєстрацію причепа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='clients.counterparty', verbose_name='Перевізник / Власник')),
            ],
            options={
                'verbose_name': 'Причіп / Напівпричіп',
                'verbose_name_plural': 'Причепи / Напівпричепи',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Повна назва ТЗ')),
                ('plate_number', models.CharField(db_index=True, max_length=25, verbose_name='Державний номер авто')),
                ('vin_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='VIN-код')),
                ('registration_certificate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Техпаспорт')),
                ('carrying_capacity_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вантажопідйомність (кг)')),
                ('has_adr', models.BooleanField(default=False, verbose_name='Має допуск ADR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.counterparty', verbose_name='Перевізник / Власник')),
            ],
            options={
                'verbose_name': 'Транспортний засіб',
                'verbose_name_plural': 'Транспортні засоби',
                'ordering': ['plate_number'],
            },
        ),
    ]
