# Generated by Django 5.1.15 on 2026-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='ID компанії-експедитора')),
                ('name', models.CharField(max_length=255, verbose_name='Назва компанії')),
                ('is_client', models.BooleanField(default=False, verbose_name='Клієнт')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Перевізник')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
                'ordering': ['name'],
            },
        ),
    ]
