# Generated by Django 5.1.15 on 2026-09-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties_at_location', to='directory.location', verbose_name='Юридична адреса компанії'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties_with_banking', to='directory.bankingdetail', verbose_name='Основні банківські реквізити'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_counterparties', to='directory.contact', verbose_name='Головна контактна особа'),
        ),
    ]
